# Generated by Django 5.0.6 on 2024-07-19 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailApp', '0003_remove_consultant_consultant_name_consultant_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultant',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
